name: Build ZMK firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install west
        run: pip3 install west

      - name: Initialize west
        run: west init -l config

      - name: Update west dependencies
        run: west update

      - name: Build firmware
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=meteorite40

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: build/zephyr/zmk.uf2